### PR TITLE
Add nullable conversion extension methods for strings and objects

### PR DESCRIPTION
**Pull request by Kobus-Smit**
This commit introduces a set of extension methods that allow strings and objects to be converted to nullable numeric, boolean, DateTime, and char types. It includes various forms for local, invariant, and provider-supported locales. Additional tests are also included.

### CODE REVIEW

**Comment by Kobus-Smit** [comment]
Hi @dimitrietataru, thank you for this useful project!

I have used it in other projects and noticed that I sometimes needed nullable versions, so thought I would contribute :)

**Comment by dimitrietataru** [comment]
Hello @Kobus-Smit 

Thank you for your PR. It's always welcome to have community involvement and new ideas in the project.
I looked at the PR and partially reviewed it. I want to discuss the implications and usability of the new methods.

For example:
``` csharp
public static bool? ToNullableBoolean(this string? value, IFormatProvider? provider)
{
    if (string.IsNullOrWhiteSpace(value))
    {
        return null;
    }

    return value.TryConvertToBoolean(provider, out bool result) ? result : null;
}
```

For this method, this is how I would've implemented it.
``` csharp
public static bool? ToNullableBoolean(this string? @this, IFormatProvider? provider)
{
    if (string.IsNullOrWhiteSpace(@this))
    {
        return null;
    }

    return ToBoolean(@this, provider);
}
```

When data is invalid, it hides the try-catch mechanism and the result may not always be the desired one.
For this case, we should have the `ToNullableBooleanOrDefault()` method.

Your implementation looks more like `ToBooleanOrNull`, which would be a nice feature to have, and the naming is also more concise.

Let me know what you think. I am open to discussions and ideas.

**Comment by Kobus-Smit** [comment]
Hello @dimitrietataru 

> When data is invalid, it hides the try-catch mechanism and the result may not always be the desired one.
For this case, we should have the ToNullableBooleanOrDefault() method.

In my uses cases I do not want to handle exceptions for invalid data but prefer null to be returned.

> Your implementation looks more like `ToBooleanOrNull`, which would be a nice feature to have, and the naming is also more concise.

Yes, that was actually my intent and I agree the naming **makes way more sense.**  🙂


Please see ecdaeb3 as an example of the refactoring.  

`ToBooleanOrNull` now looks similiar to `ToBooleanOrDefault` 

image


It this looks better to you, I can do the rest later this week.

**Comment by dimitrietataru** [comment]
> In my uses cases I do not want to handle exceptions for invalid data but prefer null to be returned.  

I do not plan to use these extension methods (for now), and the implementation you proposed makes sense as it is.

> It this looks better to you, I can do the rest later this week.  

It looks way better. Also, I like that there are no new classes/files. Just add the `ToXOrNull()` method right after the `ToXOrDefault` method (in extension classes, and also in tests).  

Thank you!

**Comment by Kobus-Smit** [comment]
Hello @dimitrietataru , I've done the rest. 

I wish an AI bot was already good enough to do this repetitive work! 😁

**Comment by dimitrietataru** [comment]
Great effort!
I will include all the changes in the next release.

**Pull request merged**
